name: CI

on: [pull_request, issues]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: ls -al
    - name: Git status
      run: git status
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
